---
name: admin_application_settings_service_usage_data_center
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78747
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/351268
milestone: '14.8'
type: development
group: group::product intelligence
default_enabled: false
