---
name: ci_pipeline_merge_request_presence_check
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78574
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/350734
milestone: '14.8'
type: development
group: group::pipeline execution
default_enabled: true
