---
name: geo_token_user_authentication
introduced_by_url:
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/351450
milestone: '14.8'
type: development
group: group::geo
default_enabled: false
