---
name: lfk_fair_queueing
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/79116
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/351082
milestone: '14.8'
type: development
group: group::sharding
default_enabled: false
