---
name: remove_import_data_on_failure
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/80074
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/352156
milestone: '14.8'
type: development
group: group::source code
default_enabled: false
