---
name: usage_data_i_code_review_user_jetbrains_api_request
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/78713
rollout_issue_url:
milestone: '14.8'
type: development
group: group::code review
default_enabled: true
